name: Go package

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  BINARY_BRANCH: binary

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo

      - name: Upload Application
        uses: actions/upload-artifact@v3
        with:
          name: application
          path: |
            dashboard
            static-content/
      - name: push branch
        run: |-
          exists=$(
            git fetch origin ${{ env.BINARY_BRANCH }} &&
            echo true ||
            echo false
          )
          if ! "$exists"; then
            git switch --orphan ${{ env.BINARY_BRANCH }}
            git commit --allow-empty -m "Initial commit"
            git push -u origin ${{ env.BINARY_BRANCH }}
          fi
          git switch ${{ env.BINARY_BRANCH }}
          git add dashboard
          git add static-content/
          git commit -m 'update: アプリケーションを更新'
          git push -f
