name: Go package

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

permissions:
  contents: write

env:
  BINARY_BRANCH: binary

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo

      - name: Upload Application
        uses: actions/upload-artifact@v3
        with:
          name: application
          path: |
            dashboard
            static-content/
            docker/Dockerfile.local
      - name: create branch
        run: |-
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          exists=$(
            git fetch origin ${{ env.BINARY_BRANCH }} 2> /dev/null &&
            echo true ||
            echo false
          )
          if "$exists"; then
            git push origin --delete ${{ env.BINARY_BRANCH }}
          fi
          git switch --orphan ${{ env.BINARY_BRANCH }}
      - name: get resources
        uses: actions/download-artifact@v3
        with:
          name: application
          path: .
      - name: push branch
        run: |-
          mv docker/Dockerfile.local Dockerfile
          git add dashboard
          git add static-content/
          git add Dockerfile
          git commit -m 'update: アプリケーションを更新'
          git push -u origin ${{ env.BINARY_BRANCH }}
